README.md
Use `<kbd>` tag and add macOS shortcut keys.
=> docs: update shortcut keys

client/components/ComponentsList.vue, client/pages/modules/imports.vue
=> chore: update nuxt logo

src/runtime/shared/hooks.ts
Resolves #64
Performance api degradation in lower versions of node
=> fix: `performance` downgrade

client/components/ComponentItem.vue, client/components/ComponentsList.vue, client/components/ComposableItem.vue, client/components/CurrentRoute.vue, client/components/HooksTable.vue, client/components/IframeView.vue, client/components/ModuleItem.vue, client/components/Notification.vue, client/components/PluginItem.vue, client/components/RoutesTable.vue, client/composables/state.ts, client/nuxt.config.ts, client/pages/modules/components.vue, client/pages/modules/custom-[name].vue, client/pages/modules/imports.vue, client/pages/modules/modules.vue, client/pages/modules/pages.vue, client/pages/modules/payload.vue, client/pages/modules/runtime-configs.vue, client/pages/modules/virtual-files.vue
=> refactor: remove reactivity transform

client/tsconfig.json
=> docs: link updated

client/pages/__inspecting.vue, src/runtime/plugins/view/Frame.vue, src/types.ts
=> fix: cannot close component inspector

packages/devtools/client/pages/modules/overview.vue
=> chore: add GitHub repo and tips for shortcut

packages/devtools/client/layouts/default.vue, packages/devtools/client/nuxt.config.ts, packages/devtools/client/pages/modules/virtual-files.vue, packages/devtools/client/splitpanes.d.ts, packages/devtools/client/styles/global.css, packages/devtools/package.json, pnpm-lock.yaml
Hi :wave: ! Following https://github.com/nuxt/devtools/pull/82 , this PR adds splitpanes to the client for resizable columns.
=> feat(client): add splitpanes for resizable columns

docs/content/2.module/0.guide.md, packages/devtools/build.config.ts, packages/devtools/kit.d.ts, packages/devtools/package.json, packages/devtools/src/integrations/vite-inspect.ts, packages/devtools/src/kit.ts, packages/devtools/src/kit/index.ts
=> feat: introduce `@nuxt/devtools/kit`

packages/devtools/client/pages/modules/storage.vue
Fix broken link to nitro storage.
=> docs: fix link

packages/devtools-kit/src/_types/rpc.ts, packages/devtools/client/components/DropZone.vue, packages/devtools/client/pages/modules/assets.vue, packages/devtools/src/server-rpc/assets.ts
tried to help with [Drag & Drop to upload](https://github.com/nuxt/devtools/issues/91#issuecomment-1463495118) and file uplaod(using base64), I'm not sure if it's a good way or not, so i'm so sorry in advance for that <3
=> feat: initial drag & drop & write assets

packages/devtools/client/components/ComponentsGraph.vue, packages/devtools/client/components/ComponentsList.vue, packages/devtools/client/components/Navbar.vue, packages/devtools/client/pages/modules/assets.vue, packages/devtools/client/pages/modules/imports.vue, packages/devtools/client/pages/modules/virtual-files.vue
i thought having navbar into seperate component will help
=> refactore: refactored navbar into seperate component

docs/content/3.development/0.contributing.md
Hello, I'm opening this contribution to use pnpm in the build script, since the project uses pnpm as a package manager.
=> docs: build script to use pnpm

packages/devtools/client/components/ServerRouteDetails.vue
fetch couldn't find the route,
thank you for all your work
=> fix(server-route): added route type to url

packages/devtools/client/components/ServerRouteDetails.vue
Server routes are not work with https
=> fix: fix domain to work with https

packages/devtools/client/components/ServerRouteDetails.vue, packages/devtools/client/server/api/users/create.post.ts
there is this bug in the doamin:
=> fix(ServerRouteDetail): fix domain port & body

packages/devtools/client/pages/modules/server-routes.vue
returned response and inputs keeps when you switch route
=> fix(server-routes): persistence between route switches

packages/devtools/client/layouts/default.vue
=> fix: components in graph view style

packages/devtools/client/components/SideNavItem.vue, packages/devtools/client/components/TabIcon.vue
=> fix(ui): sidenav tooltip overlaps with title

packages/devtools/package.json, packages/devtools/src/server-rpc/server-routes.ts, pnpm-lock.yaml
@antfu is this what you meant :grin:?
=> fix: server-routes watcher

packages/devtools-kit/src/_types/client-api.ts
Changed devTools to DevTools to make it consistent across files
=> chore: typo

packages/devtools/src/runtime/plugins/view/Main.vue
Remove border from devtools anchor icon button
Will close #275
=> fix: anchor icon button style

packages/devtools/client/pages/modules/overview.vue
=> fix(overview): modules count

packages/devtools-kit/src/_types/integrations.ts, packages/devtools/client/components/ServerRouteListItem.vue, packages/devtools/client/pages/modules/server-routes.vue
showing server-rotues from other modules in `external` group
related to #252 
<details>
<summary>With routes from other modules</summary>
</details>
<details>
<summary>without</summary>
</details>
=> feat(server-routes): group routes by type

packages/devtools/client/components/ServerRouteDetails.vue
ability to preview media(image-video)
=> feat(server-routes): preview for media type

packages/devtools/client/components/PictureInPictureButton.vue
added a button to Pip flag settings link
<details>
<summary>preview</summary>
</details>
=> feat: add PiP flag settings link

packages/devtools/src/runtime/plugins/view/Main.vue
close #288 
https://github.com/nuxt/devtools/assets/38922203/58261591-873f-42aa-abe0-6790e7131244
=> fix: prevent floating panel to dragged outside of window

packages/devtools/client/pages/modules/plugins.vue
=> fix(plugins): change execution time position

packages/devtools/client/components/ServerRouteDetails.vue
I'll close #218 and seperate it into smaller PR's, sorry for that mistake 😄
this PR will help with:
- to add json-editor option to tab inputs
- add global inputs
=> refactore(server-routes): improve and simplified

packages/devtools/client/components/ServerRouteDetails.vue
=> feat(server-routes): preview for pdfs

packages/devtools/client/setup/client-rpc.ts, packages/devtools/src/runtime/plugins/view/client.ts
=> fix: open DevTools back when open file in embedded VS Code

packages/devtools-kit/src/_types/integrations.ts, packages/devtools/client/components/ServerRouteDetails.vue, packages/devtools/client/components/ServerRouteInputs.vue, packages/devtools/client/server/api/echo.post.ts, packages/devtools/client/styles/global.css
ability to write json and have type option in inputs,
(I think still there is some bugs when you switch from json to input, the change type might not work accurately in some caces)
https://github.com/nuxt/devtools/assets/38922203/e0e523df-2607-41af-866a-8246e21d0a21
=> feat(server-routes): json-editor for tab inputs

packages/devtools/package.json, pnpm-lock.yaml
Modules not being refreshed and legend z-index
=> chore(deps): bump inspect plugin to 0.7.32

packages/devtools-kit/src/_types/options.ts, packages/devtools/client/components/ServerRouteDetails.vue, packages/devtools/client/pages/modules/server-routes.vue, packages/devtools/src/constant.ts, packages/devtools/src/server-rpc/options.ts
note: in next PR, we will add Global Inputs and user will be able to manage cache settings
https://github.com/nuxt/devtools/assets/38922203/af649898-f5e8-437d-abfb-12467caf3d1a
=> feat(server-routes): display latest selected route

packages/devtools-kit/src/_types/options.ts, packages/devtools/client/pages/modules/server-routes.vue, packages/devtools/src/constant.ts
=> feat(server-routes): toggle view

packages/devtools/client/pages/modules/modules.vue
The close button cannot be clicked.
=> fix(client): close button add zIndex

packages/devtools/src/server-rpc/assets.ts
The JPEG XL image format has been added.
=> chore: add image file type jxl format to check

packages/devtools-ui-kit/src/components/NTextInput.vue, packages/devtools/client/components/ModuleInstallList.vue
=> feat: set module search field autofocus

packages/devtools/src/server-rpc/analyze-build.ts
=> fix: analyze build without git

packages/devtools/client/components/AssetListItem.vue, packages/devtools/client/pages/modules/assets.vue
Tree view for list mode in assets
<details>
<summary>screenshot:</summary>
</details>
=> feat(assets): tree view for list mode

packages/devtools/client/components/DropZone.vue, packages/devtools/client/pages/modules/assets.vue, packages/devtools/src/server-rpc/assets.ts
add watcher so it auto-update on changes
=> feat(assets): add watcher

packages/devtools/client/components/ServerRouteDetails.vue, packages/devtools/client/components/ServerRouteInputs.vue, packages/devtools/client/composables/constants.ts
ability to see the cookies and edit their values and be able to add new cookie
https://github.com/nuxt/devtools/assets/38922203/c105d8ae-f070-4818-b268-18d4644c9285
=> feat(server-routes): add cookies tab

packages/devtools/src/runtime/plugins/view/Main.vue
As the title, the panel will be stuttering when dragging on the mobile end.
=> fix: the panel is stuttering when dragging on the mobile end

packages/devtools/src/server-rpc/general.ts
=> fix: requestForAuth devServer host

packages/devtools/client/components/AssetDetails.vue, packages/devtools/client/components/ServerRouteDetails.vue, packages/devtools/client/components/StateEditor.vue, packages/devtools/client/pages/modules/assets.vue, packages/devtools/client/pages/modules/components.vue, packages/devtools/client/pages/modules/open-graph.vue, packages/devtools/client/pages/modules/payload.vue, packages/devtools/client/pages/modules/server-routes.vue
using tooltip instead of title attribute so it provides a better UI and readability
=> feat: add tooltip to buttons

packages/devtools/src/runtime/plugins/view/Main.vue
=> fix: devtools panel justify content

packages/devtools/client/composables/rpc.ts
=> fix: resolve DevTools vite loading issue with buildAssetsDir

packages/devtools-kit/src/_types/integrations.ts, packages/devtools-kit/src/_types/rpc.ts, packages/devtools/client/components/AssetDetails.vue, packages/devtools/client/components/AssetListItem.vue, packages/devtools/client/components/DropZone.vue, packages/devtools/src/server-rpc/assets.ts
related to #91 
https://github.com/nuxt/devtools/assets/38922203/2c230376-bae6-4156-9962-e8719b015022
=> feat(assets): able to edit text content

packages/devtools/client/components/ServerRouteDetails.vue
a button to copy the full url of endpoint
=> feat(server-routes): copy url button

packages/devtools/client/components/AssetDetails.vue, packages/devtools/client/components/AssetPreview.vue
Added support for audio preview.
=> feat: audio preview

packages/devtools/client/composables/utils.ts, packages/devtools/client/pages/modules/overview.vue
=> fix(overview): pluralize nouns properly

packages/devtools/client/components/docs/plugins.md
I fixed some typos and spelling and made the help tip helpful.
=> docs: update plugins.md

packages/devtools/client/components/docs/pages.md
Refactoring with Nuxt documentation and fixing typos
=> docs: update pages.md

packages/devtools/client/components/docs/components.md
Updating the help tip for components.md in a separate PR!
=> docs: update components.md

packages/devtools/client/components/docs/hooks.md
Refactoring of the hooks help notice
=> docs: update hooks.md

packages/devtools-ui-kit/src/components/NNavbar.vue, packages/devtools-ui-kit/src/unocss.ts, packages/devtools/client/components/ComponentsGraph.vue, packages/devtools/client/components/ComponentsList.vue, packages/devtools/client/pages/modules/assets.vue, packages/devtools/client/pages/modules/imports.vue, packages/devtools/client/pages/modules/open-graph.vue, packages/devtools/client/pages/modules/server-routes.vue, packages/devtools/client/pages/modules/virtual-files.vue, packages/devtools/client/uno.config.ts
=> feat(ui): NNavbar component

packages/devtools/client/plugins/floating-vue.ts, packages/devtools/src/runtime/plugins/devtools.server.ts, playgrounds/module-starter/src/runtime/plugin.ts
Related: https://github.com/nuxt/nuxt/pull/23951.
=> fix(devtools): import app utilities from `#imports`

packages/devtools/client/components/StacktraceList.vue, packages/devtools/client/components/TimelineDetailsFunction.vue, packages/devtools/client/pages/modules/error.vue, packages/devtools/src/runtime/plugins/devtools.client.ts, packages/devtools/src/runtime/plugins/view/Main.vue, playgrounds/tab-timeline/components/GlobalNav.vue, playgrounds/tab-timeline/nuxt.config.ts, playgrounds/tab-timeline/pages/error.vue
This tab allow developers to inspect rendering error even [a custom error page](https://nuxt.com/docs/getting-started/error-handling#error-page) is provided.
This requires: https://github.com/nuxt/nuxt/pull/24376
=> feat: error tab

packages/devtools/client/components/SideNav.vue
=> fix(SideNav): logo text color in light mode

packages/devtools/client/pages/modules/server-routes.vue
| Before | After |
| --- | --- |
| <img width="1440" alt="Screenshot 2023-12-08 at 9 54 54 PM" src="https://github.com/nuxt/devtools/assets/38922203/411bd5ca-3edf-46c7-b03e-690a03ecf60e"> | <img width="1440" alt="Screenshot 2023-12-08 at 9 49 21 PM" src="https://github.com/nuxt/devtools/assets/38922203/a64959d4-2512-44a2-a850-335ec1bb8138"> |
=> fix(server-routes): improve filterByCollection for runtime routes

packages/devtools/client/app.vue, packages/devtools/client/components/DockingPanel.vue, packages/devtools/client/composables/utils.ts
registered `refresh data` & `refresh page` to command list.
=> chore(commands): register refresh page & data to command list

packages/devtools/client/app.vue
=> fix: update title of Eye Dropper command

docs/pages/index.vue
=> docs: fix code color on landing page

packages/devtools-ui-kit/src/components/NButton.vue
Disabled state of NButton doesn't work as expected.
=> fix(ui): disabled NButton. Also disable NuxtLink when used with `to`.

docs/content/index.yml
=> chore: typo in index.yml

docs/content/2.module/0.guide.md
closed #607 .
fix example link to `Module Authors#Examples > Nuxt OG Image Playground`.
- before: https://github.com/harlan-zw/nuxt-og-image/blob/main/src/module.ts#L136
- after: https://github.com/nuxt-modules/og-image/blob/551b5474b44b8ff3190643e861c0b453813683b0/src/build/devtools.ts#L65-L80
=> docs: fix example link to `Nuxt OG Image` (#608)

renovate.json
related nuxt/modules#887 .
The usage of [nuxt/renovate-config-nuxt](https://github.com/nuxt/renovate-config-nuxt) has been updated. Therefore, it has been fixed in this PR.
- ref: [fixed commit](https://github.com/nuxt/renovate-config-nuxt/commit/863fb61254efa17e435e4a58557a5243a4ee4655)
```suggestion
{
"$schema": "https://docs.renovatebot.com/renovate-schema.json",
"extends": [
-   "@nuxtjs"
+   "github>nuxt/renovate-config-nuxt",
]
}
```
=> chore(renovate): update extends (#610)

packages/devtools/src/runtime/plugins/view/FrameBox.vue
close #615 
https://github.com/nuxt/devtools/assets/38922203/30b9e687-b31f-4263-879e-330c1760f158
=> fix: support for resizing window in touch screen

packages/devtools-ui-kit/src/components/NSplitPane.vue
=> fix(ui): @apply conflict with tailwind

packages/devtools/src/integrations/vue-devtools.ts
introduced in https://github.com/nuxt/devtools/pull/621
resolves https://github.com/nuxt/devtools/issues/629
=> fix(devtools): do not try to overlay on server

packages/devtools/src/integrations/vite-inspect.ts
=> fix: vite-inspect iframe url

docs/content/3.development/0.contributing.md
Resolves  #605 .  Update  pnpm version listed in docs, from v7 to v8.14.1
=> docs: update pnpm version in docs

packages/devtools/client/pages/index.vue
=> fix(devtools): optimize the home page layout

packages/devtools/src/runtime/plugins/view/FrameBox.vue
=> fix(timeline): reduce warning

packages/devtools/client/components/RoutePathItem.vue
=> fix: navigate to pages with param

packages/devtools/client/components/ServerRouteInputs.vue
=> fix(server-routes): unable to clear all params

packages/devtools/client/components/social/SocialPreviewGroup.vue, packages/devtools/client/pages/modules/open-graph.vue
=> fix: OpenGraph layout

packages/devtools/client/composables/state-modules.ts
=> fix(modules): update compatibility check for Nuxt 3 and 4

packages/devtools/src/runtime/plugins/view/FrameBox.vue
I'm getting type testing errors downstream due to strictness. This resolves them.
=> chore(devtools): improve type safety on `e.touches[0]`

packages/devtools/client/middleware/route.global.ts
Redo #735 as the PR has locked branch
Close #735
=> fix: welcome page condition

packages/devtools/package.json
See on https://npm.chart.dev/@nuxt/devtools
=> chore: add missing description for package.json

packages/devtools/client/pages/settings.vue
* Add Windsurf to the list of editors
* https://codeium.com/windsurf
=> feat: add Windsurf to the list of editors

docs/content/1.guide/1.features.md
Tasks are one of my favorite features of the Nuxt devtools but they aren't documented
resolves #841
- [ x] 📖 Documentation (updates to the documentation or readme)
Tasks are one of my favorite features of the Nuxt devtools but they aren't documented
=> docs: add info about tasks feature
