client/components/ModuleItem.vue

On user modules, the cursor is not pointer but is clickable (because no href).
Here a PR to add that:

fix: use pointer cursor for user module which redirects to file

---

client/components/ModuleItem.vue

Follow-up of #51. The explicit `cursor-pointer` attr is not needed for a `<button>` ☺️

refactor: remove obsolete cursor pointer def

---

.eslintrc
README.md
src/integrations/vscode.ts
src/types.ts

Since `code-server` is having kinda random ports, I added this in docs for people to easily figure out that they can change the code-server listening port for this project

docs: module options

---

src/runtime/shared/hooks.ts

Fixed `performance` api downgrade in node env.
In https://github.com/nuxt/devtools/pull/66 pr, I made the mistake of only considering the `performance` api compatibility in the browser environment. I am sorry about that.

fix: `performance` downgrade in node env

---

client/pages/modules/virtual-files.vue

HI :wave: small UI improvement in the VFS part.
A lot of file path are quite long and are hidden since it does not have enough space to show up. 
This PR adds the CSS `resize` property to give us the ability to resize the file path column

feat(client): allow file column resize in VFS

---

packages/devtools/client/components/Drawer.vue

sticky header so we can access devtool dropdown or closing button when we scroll down

feat: sticky drawer header

---

docs/content/0.index.md
docs/content/3.development/0.contributing.md
docs/content/3.development/_dir.yml
local.ts

Fix `developement` into `development`.

docs: fix typo

---

packages/devtools/client/components/ServerRouteDetails.vue

when route.method is not defined, it's a dropdown,
also removed domain from shown url

fix(server-routes): add method dropdown

---

packages/devtools-wizard/src/global.ts

Running `nuxi devtools enable` on a new install with `nuxt@^3.4.0` makes uses of global `markDisable` function, which tries to read `devtoolsGlobal.projects` from `~/.nuxtrc`. This fails when the `devtoolsGlobal` object does not exist, yielding
`cannot read property of undefined (reading 'projects')` error.
This commit updates the `markDisable` function to safely access RC file properties.

fix(wizard): builtin `enable` setup fails on new installs

---

packages/devtools-kit/src/_types/rpc.ts
packages/devtools-kit/src/_types/server-ctx.ts
packages/devtools/client/setup/client-rpc.ts
packages/devtools/src/integrations/vscode.ts
packages/devtools/src/runtime/plugins/view/Frame.vue
packages/devtools/src/server-rpc/general.ts
packages/devtools/src/server-rpc/index.ts

Now the VS Code integrations auto install https://github.com/antfu/vscode-server-controller extension and communicate with it to do the navigation
https://user-images.githubusercontent.com/11247099/235331465-6b47402c-a683-4db6-a76d-2429d20dbd10.mp4

feat: open in file in embeded vscode

---

packages/devtools/client/components/SideNav.vue

click on iframe was not closing the DockingPanel component,
is this ok or should we go with something more like this?
```vue
<button
i-logos-nuxt-icon my3 h-6 w-6 pb-2 text-lg
:class="client ? '' : 'saturate-0'"
:title="client ? 'Nuxt DevTools' : 'DevTools Client not connected, try open it in iframe mode'"
@click="show = !show"
/>
<Teleport to="body">
<div ref="panel" v-lazy-show="show" absolute left-15 top-2 z-100 border border-base rounded text-black shadow bg-base dark:text-white>
<div absolute left--2 top-3 h-2 w-2 border="l t b base" bg-base />
<DockingPanel ml2 />
</div>
</Teleport>
```

fix: DockingPanel clickoutside on iframe

---

packages/devtools/client/pages/modules/storage.vue

fix nitro storage link
https://nitro.unjs.io/guide/introduction/storage => https://nitro.unjs.io/guide/storage

fix: nitro storage link

---

packages/devtools-ui-kit/src/assets/styles.css
packages/devtools-ui-kit/src/components/NDarkToggle.vue
packages/devtools/client/components/DockingPanel.vue
packages/devtools/client/pages/settings.vue
packages/devtools/src/runtime/plugins/view/Container.vue
packages/devtools/src/runtime/plugins/view/Frame.vue

Ported from https://github.com/vuejs/vitepress/pull/2347, thanks to @hooray
https://github.com/nuxt/devtools/assets/11247099/c18c682b-2599-42fa-9f9f-3bf540b62bf8

feat: add dark/light mode switch transition

---

packages/devtools-ui-kit/src/components/NDarkToggle.vue
packages/devtools-ui-kit/src/components/NSwitch.vue
packages/devtools-ui-kit/src/unocss.ts
packages/devtools/client/pages/settings.vue

fix(style): switch, radio, checkbox hover style

---

package.json
packages/devtools/client/composables/npm.ts
packages/devtools/client/composables/rpc.ts
packages/devtools/client/composables/state-modules.ts
packages/devtools/client/pages/modules/analyze-build.vue
packages/devtools/client/pages/modules/storage.vue
packages/devtools/package.json
packages/devtools/src/constant.ts
packages/devtools/src/module-main.ts
packages/devtools/src/server-rpc/index.ts
pnpm-lock.yaml

close #112, close #193
The downside is that we are temporarily unable to provide the disconnection state (await for https://github.com/vitejs/vite/pull/13334)

refactor: reuse Vite's websocket

---

packages/devtools/client/composables/storage.ts
packages/devtools/src/runtime/plugins/view/utils.ts

click outside is not working once you have close the window and reopen it, and if we move the panel state position and click on close outside option, it would reset it,
thanks to #273
https://github.com/nuxt/devtools/assets/38922203/a797f39c-ab44-4a38-96be-54371893518c

fix: devtools close on outside click

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature-suggestion.yml
.github/ISSUE_TEMPLATE/help-wanted.yml

copy the templates from [ionic module](https://github.com/nuxt-modules/ionic/tree/main/.github/ISSUE_TEMPLATE), thanks to daniel for this
I remove `assignees` as I didn't know who to add

chore: add issue templates

---

packages/devtools-kit/src/_types/options.ts
packages/devtools/client/components/ComponentsGraph.vue
packages/devtools/src/server-rpc/ui-options.ts

close #188 
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
both component are global
</details>

fix(ComponentGraph): show global components in different color

---

packages/devtools/client/components/ServerRouteListItem.vue
packages/devtools/client/pages/modules/server-routes.vue

if you have multiple paths with the same name, but different methods, selecting one of them, will always select the first one on the list, no matter what.
Before:
https://github.com/nuxt/devtools/assets/35883748/af687591-6420-4142-81d2-9c98a8c0dc74
After:
https://github.com/nuxt/devtools/assets/35883748/ea10f9ba-06ad-4942-8b63-f260c93a4199

fix(server-routes): fixed same path different methods

---

packages/devtools/client/components/ServerRouteDetails.vue

when you switch the body input type to boolean, it seems to work fine for `true` value but when you check the box to off, it sends `undefined` instead of `false` 
Before:
https://github.com/nuxt/devtools/assets/35883748/d5781658-e365-47cd-82d1-a9334ee46dff
After:
https://github.com/nuxt/devtools/assets/35883748/003f80cf-9206-463e-820a-e5aa9f206994

fix(server-routes): fixed boolean undefined value

---

packages/devtools/client/components/social/SocialTwitter.vue

The built-in open graph preview is great, but I found a subtle difference between the twitter style and how it appears on the Twitter site.
I made a few adjustments to make it more consistent with the twitter style:
- Maximum number of lines of description text changed from 3 to 2
- Image resizing to 129px
- Font size adjusted to 15px
- Line height adjusted to 20px
- Rounded corners adjusted to 16px
- Adjusted the gap of flex to 2px
- Use twitter's default font
**snapshot**
Before:
After:

chore: update the og style of twitter

---

packages/devtools/src/server-rpc/general.ts

Resolves #326 (+ takes into account a possibility of different host)

fix: respect Nuxt's `devServer` config when creating request for auth URL

---

packages/devtools/client/pages/modules/server-routes.vue

the current filtering would be like: (if there is multiple files with same name e.g. [id], it would add it to one collection and I think this would make things complicated)
so in this update, only the dirs will be as collection:

fix(server-routes): filter only dir as collection

---

packages/devtools/src/server-rpc/npm.ts

Resolve #331 
Implemented an install queue: I added an installQueue where the module name is pushed into the queue when the module starts installing. When the module installation is complete, the module name is removed from the queue.
Only when all modules are installed is the new configuration written to the file. This prevents an automatic reboot when updating the config, which would result in only one module being installed.

feat: install modules at once

---

packages/devtools-kit/build.config.ts
packages/devtools-kit/src/_types/client-api.ts
packages/devtools-ui-kit/src/components/NCodeBlock.vue
packages/devtools/client/composables/client-services/shiki.ts
packages/devtools/client/composables/client.ts

As far as I could tell, `lines` and `theme` don't do anything.
We also type the supported langs because we can.

fix(kit): types for `renderCodeHighlight`

---

packages/devtools-kit/src/runtime/iframe-client.ts

Currently the type is broken because it's loading the interface from a broken path.
```ts
import type { NuxtDevtoolsIframeClient } from '../../src/_types/client-api';
```
See https://unpkg.com/browse/@nuxt/devtools-kit@0.7.0/dist/runtime/iframe-client.d.ts.

fix(kit): broken types for `useDevtoolsClient()`

---

packages/devtools-ui-kit/src/components/NDialog.vue
packages/devtools/client/components/DrawerRight.vue

Seems like the introduction of the focus trap on NDialog stopped the dialog closing when clicking on the backdrop.
[Peek 2023-07-27 14-46.webm](https://github.com/nuxt/devtools/assets/5326365/902208b9-7580-4f87-91ce-8e95a879af78)
(I'm clicking on the backdrop in the video)
To fix it we implement the same logic that the DrawerRight component uses. We also fix some i18n issues and have better styling for dark mode.

fix(ui-kit): dialog closing and a11y

---

packages/devtools/client/components/AssetDetails.vue
packages/devtools/client/components/AssetPreview.vue

Add support for preview video assets.
**Before**
**After**

feat: support preview video assets

---

packages/devtools/client/components/StateEditor.vue

**Current Issue**
Currently, StateEditor can only edit json like data.
However, we often store data of type string or number. If the value is an empty string or a number, "No data" is displayed. If you define `useState('test:undefined', () => undefined)`, it even make the whole tab won't display.
In fact, we probably don't need "no data", because even if it's an empty array, object or even `undefined` or `null`, we should still be able to append data or edit it.
---
**What I did**
- In this pr, I make sure that numbers and strings are edited properly and remain reactive.
- Now "no data" will not be displayed so that we can edit empty arrays or objects.
---
**legacy issue**
There are still issues that have not been addressed:
Empty strings and undefined data currently show a strange …

feat: enhance state editor

---

packages/devtools/client/composables/state-tabs.ts

- Fixed a bug that "pinned" catalog could not be hidden by switch.
- Fixed a bug that hiding the "app" catalog would also hide the "pinned" catalog.

fix: pinned tabs filter

---

packages/devtools/client/components/ServerRouteDetails.vue

it was causing the error status to stay after error was resolved, missed that sorry

fix(server-routes): clear error onResponse

---

docs/content/1.guide/0.index.md

Submitting a simple change to a link.
- Updates the link in the documentation for the types file to go directly to the file that contains the module options types.

docs: update 0.index.md

---

packages/devtools-kit/src/_types/client-api.ts
packages/devtools-kit/src/_types/options.ts
packages/devtools/client/composables/storage.ts
packages/devtools/client/pages/settings.vue
packages/devtools/src/constant.ts
packages/devtools/src/runtime/plugins/view/Main.vue
packages/devtools/src/runtime/plugins/view/client.ts
packages/devtools/src/runtime/plugins/view/state.ts
packages/devtools/src/types/ui-state.ts

I found that, sometimes, the floating panel took a bit too much space from the app. So I am thinking of having a way to minimize it when not in use for a while.
The effect looks like this (shorten the timeout to 2s for demo):
https://github.com/nuxt/devtools/assets/11247099/4cbafb99-0f92-4666-bd4c-8064db0e78cf
I'd like to hear your opinion on this, and if we should make it configurable?

feat: minimize panel on inactive

---

packages/devtools/client/components/AuthConfirmDialog.vue
packages/devtools/client/components/AuthRequiredPanel.vue
packages/devtools/client/composables/dev-auth.ts
packages/devtools/client/composables/dialog.ts

the `AuthConfirmDialog` UI is diffrent than `AuthRequiredPanel`(for example it doen't have an input for manuel token), not sure if it was on purpose
old UI:
the current UI looks like:

fix: add AuthRequiredPanel to AuthConfirmDialog

---

packages/devtools/client/components/Notification.vue

The `Dialog` z-index is higher than `Notification` component and sometimes it make the notification disappear

fix: notification z-index

---

packages/devtools/client/composables/rpc.ts

fix: find vite client path from subframe parent

---

packages/devtools/package.json
packages/devtools/src/integrations/analyze-build.ts
packages/devtools/src/utils/fs.ts
pnpm-lock.yaml

For nuxt's analyze-build scenario, where the number of files is not particularly large, the native node fs implementation of getFolderSize is fast enough for humans.
Using fast-folder-size is partly a matter of open-source protocols → #403 
On the other hand, it's not friendly to windows users, it requires downloading the binary, which can be particularly slow in some areas.

refactor: internal implementation of getFolderSize, close #403

---

packages/devtools/client/pages/settings.vue

make sure client has value to prevent from getting error `"Cannot read properties of undefined (reading 'app')"`

fix(settings): make sure client has value

---

packages/devtools-ui-kit/package.json
pnpm-lock.yaml

`@nuxt/devtools` should be a `devDepedency` in `@nuxt/devtools-ui-kit`, it appears.

fix(deps): set `@nuxt/devtools` as `devDependency`

---

docs/pages/index.vue
packages/devtools-kit/src/_types/options.ts
packages/devtools/client/pages/index.vue
packages/devtools/client/pages/settings.vue
packages/devtools/client/unocss.config.ts
packages/devtools/src/constant.ts
packages/devtools/src/module-main.ts
packages/devtools/src/runtime/plugins/view/Main.vue
packages/devtools/src/runtime/settings.ts
packages/devtools/src/server-rpc/options.ts
packages/devtools/src/utils/local-options.ts

When we ship DevTools by default in Nuxt 3, we want to minimize the distribution for regular development workflow as much as possible. In that case, we don't want all users to get the floating panel in their apps without knowing the existence of Nuxt DevTools.
In this PR, we make the panel hide by default, except when `devtools: { enabled: true }` or `modules: ['@nuxt/devtools']` is presented in the config (indicate that the users are aware of and want to use devtools).
Combining with https://github.com/nuxt/devtools/commit/97b3e186e8798142c54d2599329ca97c97ea4b59, we are showing the hint in both the terminal and browser console. For the first time a user opens up DevTools, a welcome page will be displayed and ask to turn on the floating panel.

feat: hide panel by default when not explicit enabled

---

packages/devtools/client/components/ServerRouteDetails.vue

using `window?.location.origin` for domain so that in cases like address forwarding works too.
closes #445

fix(server-routes): use window.location.origin for doamin

---

packages/devtools/src/server-rpc/assets.ts

I think before the watch hook key had srcDir with it, but now it is only the publicDir (e.g. public/nuxt.svg) so watcher was not working.

fix(assets): watcher

---

packages/devtools/client/components/docs/imports.md

docs: typo

---

packages/devtools-ui-kit/src/components/NDialog.vue

`n-dialog` is not a valid class, replace it with `n-glass-effect` to get the backdrop effect

fix(ui): dialog backdrop

---

packages/devtools-kit/src/_types/integrations.ts
packages/devtools/client/components/ModuleInstallList.vue
packages/devtools/client/components/ModuleItemBase.vue
packages/devtools/client/composables/state-modules.ts

Introducing the ability to sort modules in the installation list based on key metrics such as module downloads, stars, publication time, and creation time.
https://github.com/nuxt/devtools/assets/38922203/9616470f-b6f0-4825-9629-b8c731141a46

feat(modules): dynamic sorting for module installation list

---

packages/devtools-kit/src/_types/integrations.ts
packages/devtools/client/components/ServerRouteDetails.vue
packages/devtools/client/components/ServerRouteInputs.vue
packages/devtools/client/pages/modules/server-routes.vue

This PR introduces a new feature to server-routes inputs, allowing users to active/passive an input. when activated, the input is in the request; otherwise, it will be excluded.
note: the cookies tab doesn't have an active/passive checkbox, do you think it's needed?
https://github.com/nuxt/devtools/assets/38922203/bb05b785-1408-4060-aee3-d9c94842fdf5

feat(server-routes): add optional checkbox for inputs

---

packages/devtools/client/components/social/SocialPreviewGroup.vue
packages/devtools/client/components/social/SocialTelegram.vue

layouting from: https://web.telegram.org/k/#@WebpageBot
devtools:

feat: add `telegram` social preview  tab

---

packages/devtools/src/runtime/plugins/view/FrameBox.vue
packages/devtools/src/runtime/plugins/view/Main.vue
packages/devtools/src/runtime/plugins/view/utils.ts

close #411
Eliminate the side effects of element transformations by calculating the offset of the element.
https://github.com/nuxt/devtools/assets/64941905/316e24b8-fa84-4b41-b1bf-156e4e790fa0

fix: blurred font

---

docs/content/1.guide/1.features.md

docs(features): vs code server

---

packages/devtools/src/server-rpc/assets.ts

`.` from `ext` was blocking `defaultAllowedExtensions` to gt upload.
> sorry I forgot to add `.slice(1)` in the main PR #391 
note: sometimes there are some small fixes(or mistakes like this), should I open PR or commit directly? \cc @antfu

fix(assets): remove dot from file extension

---

docs/pages/index.vue

Use the right `idx` as an active indicator.
https://github.com/nuxt/devtools/assets/11806619/83a69731-4724-4245-bb0f-df154c336f62
There's also an issue where `https://devtools.nuxt.com/_ipx/_/images/imports.webp` results in a 404 error in the production build, but I can't determine the cause.

fix(doc): active status of project cards

---

docs/content/2.module/0.guide.md

added `nuxt-mongoose` as an example, also should we add [`nuxt-devtools-pinia`](https://www.npmjs.com/package/nuxt-devtools-pinia) too ?

docs: add `nuxt-mongoose` to examples

---

packages/devtools/client/components/PictureInPictureButton.vue

fix(pip): check for https support

---

packages/devtools/src/dev-auth.ts
packages/devtools/src/utils/local-options.ts

* Issue #493 
Add support for XDG_CONFIG_HOME env variable. 
If detected, local options will be saved under `XDG_CONFIG_HOME/.nuxt/devtools`. If not, `homedir()/.nuxt/devtools` will be used (current behaviour).

feat(devtools): support for xdg-home-config

---

packages/devtools/client/components/ServerRouteDetails.vue

https://github.com/nuxt/devtools/assets/38922203/b7391def-242e-4de6-9a09-14eaa2b33c7c

feat(server-routes): implement persisting input values in localStorage

---

packages/devtools/package.json

when accessing type completion for `devtools` it is typed as `any` because there is no default export in `dist/types.d.ts`.
When using bundler module resolution, it works fine as the types file is `dist/module.d.ts` instead.

fix(devtools): update default types to `module.d.ts`/`.mts`

---

packages/devtools/src/runtime/function-metrics-helpers.ts

This PR fixes bug of usage `timeline` option with `useAsyncData` with `lazy: true`
Case if bug:
- `useAsyncData` returns only promise, without data, pending and others
- [Reproduction branch](https://github.com/Vespand/devtools/tree/fix/timeline-helper-wrapper-reproduction) - added reproduction in `./playgrounds/empty` (JFI - it only works on local machine, in stackblitz timeline metrics can't be enabled)
- `useAsyncData()` return not only promise, it also return a lot additional attributes, like `data`, `pending`, `error`, example:
- After use `useAsyncData()` with metrics wrapper returning value is only promise, example with timeline enabled:
- Without `timeline: { enabled: true } }` all working as expected
This happens, because `.finally()` returns only Promise, without additional …

fix(timeline-helper-wrapper): Fix return value in timeline wrapper for promises

---

packages/devtools-ui-kit/playground/pages/index.vue
packages/devtools-ui-kit/src/components/NTextInput.vue

Pass autocompete attribute to input element.
That removes this warning :

feat(ui): added autocomplete props to NTextInput component

---

packages/devtools/client/styles/global.css

A very very small fix, but which gave me a hard time struggling with eslint.
That fix the black arrow in light mode.

fix: floating-vue arrow style

---

packages/devtools-ui-kit/build.config.ts

We can't export detvools-ui-kit in external project without the composables. It throw this error when including the component `NNotification` :
```bash
ERROR  Pre-transform error: Failed to resolve import "../composables/notification" from "../../node_modules/.pnpm/@nuxt+devtools-ui-kit@1.0.8_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.5_fuse.js@7.0.0_idb-k_hp7eiil6i4mqmffgl7noc2tkui/node_modules/@nuxt/devtools-ui-kit/dist/components/NNotification.vue". Does the file exist?
```
This pull request fix this issue.
It doesn't seem to have an impact to the devtools client...

fix(ui): Added composable to build config

---

packages/devtools/src/integrations/vite-inspect.ts

If there is a buildAssetsDir defined in the config the inspect tab in devtools throws 404 as the 'buildAssetsDir' is hardcoded.

fix: inspect tab when custom buildAssetsDir is configured, fixes #589

---

packages/devtools/client/styles/global.css

At #578, I fixed the light mode, but introduced a bug in dark mode!
The linter suggested to me to wrap with single quotes, but it breaks `--at-apply` at build time.
I double-checked light and dark mode for this pull request.
This tiny change gave me some headaches. I hope it's the last one! :disappointed_relieved:

fix: floating-vue arrow style in dark

---

packages/devtools/src/runtime/plugins/view/client.ts

This pull request removes the line mentioned in #583 and fix the `open` issue.
In fact, the `watchEffect` in FrameBox.vue trigger when the `state.value.open` change and it will sync the client throw the `getIframe()` function. So, setting the `state.value.open` line 68 is enough to open the devtools.

fix: remove unnecessary line + open devtools calling twice `syncClient`

---

packages/devtools/client/components/IframeView.vue

This PR provides a default label to the iframe to not hurt accessibility score in development. This will hopefully improve DX by only letting the real errors show, as devtools are not included in production.

fix: provide a label for accessbility

---

package.json
pnpm-lock.yaml

Attempting to follow the [Contribution Guide](https://devtools.nuxt.com/development/contributing#monorepo) and run:
>```sh
>pnpm i
>pnpm run build
>```
on a new clone of the project on Node v18.19.0+ will result in the following error message (after some logs):
```
node:internal/process/esm_loader:40
internalBinding('errors').triggerUncaughtException(
^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
at V (file://{project root}/node_modules/.pnpm/tsx@4.1.1/node_modules/tsx/dist/esm/index.mjs:1:1956)
at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
at Hooks.register (node:internal/modules/esm/hooks:168:16)
at async initializeHooks (node:internal/modules/esm/utils:167:5)
at async customizedModuleWorker …
```

fix: override `tsx` dependency to known fixed version (broken on Node v18.19.0+)

---

packages/devtools/client/app.vue

Some tabs (precisely server routes and server-tasks, maybe more) were overflowing of the iframe.
I tried using `overflow: hidden` without success, but adjusting the border-radius match worked.
Before vs after:

fix: devtools border-radius

---

docs/pages/index.vue

this PR
- fixes `border-radius` of `LandingCTA`. 
- fixes `shadow` of `Card`
| before | after |
:--------------:|:-------------:

docs: update ui-pro ui props

---

packages/devtools/client/pages/modules/pinia.vue

Cover the use cases: 
```ts
modules: [
['@pinia/nuxt', {
autoImports: [
'defineStore',
],
}]
```

fix(client): pinia panel visible logic

---

packages/devtools-kit/src/_types/integrations.ts
packages/devtools-kit/src/_types/rpc.ts
packages/devtools/client/components/ServerTaskDetails.vue
packages/devtools/client/components/ServerTaskListItem.vue
packages/devtools/client/composables/state.ts
packages/devtools/client/pages/modules/server-tasks.vue
packages/devtools/src/server-rpc/index.ts
packages/devtools/src/server-rpc/server-tasks.ts
packages/devtools/src/types/tasks.ts

When used in a regular project, the devtools try to fetch `http://localhost:3000/__nuxt_devtools__/client/_nitro/tasks` which is wrong (Returns 200 text/html).
This PR makes the switch to use RPC like other features.
Note: This also enabled open in editor feature as RPC provides the task's file path 

fix: use RPC to get tasks

---

packages/devtools/src/server-rpc/server-tasks.ts

Types provided by nitro don't reflect the situation on the shape of nitro tasks options. Here, `Object.entries(undefined)` throws an error.
I will update the types on Nitro after this PR.
Note: this PR doesn't need to be merged if the fix is provided upstream on nitro, this is just a patch in the meanwhile

fix: scheduledTasks can be undefined

---

packages/devtools/client/pages/modules/pinia.vue

it was throwing an error: `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'includes')`

fix(pinia): pinia module searching null safety

---

packages/devtools/client/components/PictureInPictureButton.vue

Moving the devtools to picture in picture mode is really great :rocket: 
But why limit this feature only for https ?
[DocumentPictureInPicture](https://developer.mozilla.org/en-US/docs/Web/API/DocumentPictureInPicture) is allowed only in [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), but **localhost is a secure context**.
This pull request uses [window.isSecureContext detection](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#feature_detection) instead of relying on the location protocol.
Tested on nixOS with the most recent versions of Chromium, Google Chrome and Vivaldi.

feat: enable picture in picture for localhost

---

packages/devtools/src/server-rpc/assets.ts

We are planning to move to [emitting absolute paths in `builder:watch` in Nuxt v4](https://github.com/nuxt/nuxt/issues/25339). You can see a little more about the history in the PR linked in that issue.
This PR is an attempt to use a forward/backward compatible approach, namely resolving the path to ensure it's absolute, then making it relative so your existing code will continue to work.
This should be safe to merge as is, but do let me know if you have any concerns about this approach.

fix: adopt forward-compatible approach to `builder:watch`

---

packages/devtools/client/app.vue
packages/devtools/src/runtime/function-metrics-helpers.ts
packages/devtools/src/runtime/use-nuxt-devtools.ts

This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …

fix: opt in to `import.meta.*` properties

---

packages/devtools/src/runtime/plugins/view/Main.vue
packages/devtools/src/runtime/plugins/view/client.ts

Currently when printing a page in dev-mode with nuxt the holder to open the dev-tools will be printed as well which often results in additional empty pages containing just the holder.
Please let me know if I should adjust the approach to something else.

feat: hide devtools when printing

---

packages/devtools/client/components/ModuleInstallList.vue

Add sortFn option in fuse.js to sorted search result in list by sorting options, also threshold option avoid to show less relevance modules, but not sure if 0.2 is an appropriate value(if no threshold basically all modules will be displayed and will break sorting options😇)
fixed #669

fix: sort items in fuse

---

packages/devtools-kit/package.json
packages/devtools/package.json
pnpm-lock.yaml
scripts/bump-edge.ts

Related https://github.com/nuxt/nuxt/issues/27597

ci: relax `nuxt` peerDeps version to support edge releases

---

packages/devtools-ui-kit/package.json
packages/devtools-ui-kit/src/components/NDarkToggle.vue
packages/devtools-ui-kit/src/module.ts
packages/devtools/client/components/ServerRouteDetails.vue
packages/devtools/client/components/ServerTaskDetails.vue
packages/devtools/client/components/StateEditor.vue
packages/devtools/client/components/StorageDetails.vue
packages/devtools/client/components/TimelineArgumentView.vue
packages/devtools/package.json
pnpm-lock.yaml

This PR fixes the glitch between darkMode and lightMode (closes #482) by removing `@nuxtjs/color-mode` and standardizing on `useColorMode` from `@vueuse`
- plus a custom storageKey (`nuxt-devtools-color-mode`) is now used for devtools.

fix: color mode

---

packages/devtools/client/components/ComponentsGraph.vue

closes #693 
this PR adds highlighting functionality to component graph when a component is searched. the highlighted component will be shown in `purple`
| Dark Mode  | Light Mode |
| ------------- | ------------- |
| <img width="1687" alt="Screenshot 2024-07-21 at 7 11 08 PM" src="https://github.com/user-attachments/assets/8370bbce-5950-477c-9772-a92276a1332a">  | <img width="1679" alt="Screenshot 2024-07-21 at 7 10 42 PM" src="https://github.com/user-attachments/assets/2feb4583-146b-4963-9cff-6ce34d519321">

feat: add search functionality to components graph

---

packages/devtools/client/components/StateEditor.vue

this should fix #710 
Note: I didn't use this tab much so I wasn't sure about the functionality, right now if we edit a value in JsonEditor (for example something in Public Runtime Config), the prop.state is not getting updated. is that intended?

fix(state-editor): update deepSync function

---

packages/devtools/client/components/StateEditor.vue

fix: handle null in deepSync

---

docs/content/1.guide/0.getting-started.md

Added header for showing devtools window
N/A
I stumbled on this project as a new Nuxt developer. Took me 3 scans through the documentation to find how to open the devtools window.
Adding the header makes this clearer

Update 0.getting-started.md with header for opening the devtools window

---

packages/devtools/client/setup/vue-devtools.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Be related to https://github.com/vuejs/devtools/pull/693
Close #724

fix: missing pinia store modules

---

packages/devtools/client/composables/utils.ts
packages/devtools/client/pages/modules/pages.vue
packages/devtools/src/wizard/enable-pages.ts
playgrounds/v4/.npmrc
playgrounds/v4/nuxt.config.ts
playgrounds/v4/package.json
playgrounds/v4/tsconfig.json
pnpm-lock.yaml

closes #734 
this PR adds support for creating page in nuxt v4 app directory

fix: add v4 compatibility version handeling for pages tab

---

docs/content/1.guide/1.features.md
packages/devtools-kit/src/_types/integrations.ts
packages/devtools-kit/src/_types/options.ts
packages/devtools/src/integrations/vscode.ts
packages/devtools/src/server-rpc/general.ts

- fix #408
- fix #737
- fix #503 
- fix #750
Improves support for VS Code integration:
1. Support both the newer Microsoft "code" cli tool (using serve-web) and the legacy vs-code-server cli tool. 
2. Adds a new option (`codeServer`) under the vscode options object to select the server type to use: `ms-code-server` for the legacy (and existing) code-server cli, `coder-code-server` for the open-source Coder code-server and `ms-code-cli` for the VS Code cli server. 
3. Adds the root path to the repository location when going to a file from the vue-inspector, solves issue when running in a container/devcontainer.
4. Adds host option ("0.0.0.0") to the arguments to support devcontainers that try to map to ipv6 addresses by default
5. Adds the line/column to the vue-inspector click url …

feat: improves vscode integration, support multiple backends

---

packages/devtools/src/integrations/vscode.ts

- fix #408
- fix #737
- fix #503 
- fix #750
Fixes a bug in #763 - when the host parameter is not specified, the MS Code Server and MS Code CLI won't start (empty parameter is unrecognized). This change defaults the host to 127.0.0.1.

Set a default value for the vscode host parameter

---

packages/devtools/src/npm/index.ts

resolves #598 
This PR enhances the DevTools method for checking package version information by incorporating Nuxt [modulesDir](https://nuxt.com/docs/api/nuxt-config#modulesdir) setting (`nuxt.options.modulesDir`), allowing it to check version information from additional custom module directories.

feat: enhance module resolution paths for getPackageInfo

---

packages/devtools/client/components/ModuleInstallList.vue

resolves #780
I am doing interface development in Vue3. While the currently used libraries are visible in the Modules tab, I finally wondered about the "Install New Module" button. When I clicked it, I saw that all the libraries were listed.
However, I noticed that the libraries I am currently using were included in the list without being filtered. For this reason, I thought a filtered list would be nice.
The libraries in the "Install New Module" list can be filtered from those I currently use, or the list can be made cleaner with an option such as "Filter those I currently use".
| Filter Off | Filter On |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/d93c07a9-fd56-4f72-b982-44ab34eed996) | ![Image](https://github.com/user-attachments/assets/13e9f440-b36d-452f-8 …

feat: filter out installed modules in search result, closes #780

---

packages/devtools/client/nuxt.config.ts

Nuxt has switched to use `preserveModules` for Vite server build, meaning that manual chunks won't work.
I will likely revert this for this reason but it's probably safer only to customise the vite _client_ chunks.

build: only apply build output customisation to client build

---

packages/devtools/client/components/ModuleItemBase.vue

Was confused seeing module setup times in the minute range while it took less to startup and render the page 😅
The debug logs show setup time in milliseconds and these are used to display the timings as well, it looks like the duration display component accepts duration as milliseconds, so the multiplication is not necessary.

fix: module setup times are multiplied by `1000`

---

packages/devtools-kit/src/runtime/iframe-client.ts

The type of `useDevtoolsClient` in the built and published package is `Ref<any>`. This PR change the import from `@nuxt/devtools-client` to relative path

fix(devtools-kit): fix `useDevtoolsClient` return type

---

packages/devtools-ui-kit/src/components/NButton.ts

fix #851 
This PR moves `@unocss-include` into a string instead of a comment so esbuild would preserve it postbuild. 
And I feel ashamed of this workaround.

fix(ui-kit): add `@unocss-include` magic string in NButton

---

packages/devtools/client/components/StateEditor.vue

resolves #849, resolves #768
- [x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
Destructured the watched values in the callback and applied the typeof check directly on state. Now:
- If state is an object (non-null), it calls deepSync.
- If state is a primitive, it assigns proxy.value directly.
The watch callback was checking the typeof the entire array [props.revision, props.state], which always returns "object", causing it to always enter the deepSync branch — even when props.state is a primitive (e.g., string, number).

fix: watch() typeof check on array is always false

---

packages/devtools/client/components/StateEditor.vue

fixes #744 
- [x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
This PR introduces a `isPrimitive` utility function to clean up the type-checking logic in `StateEditor`, and adds support for `bigint` values as valid primitives.

fix(StateEditor): add isPrimitive helper and support bigint type (#744)

---

packages/devtools-kit/src/runtime/host-client.ts

TS or Rollup isn't able to detect the return type of `useDevtoolsHostClient` so we have to sstrongly type it

fix(devtools-kit): explicitly type return type of useDevtoolsHostClient

---

packages/devtools-kit/package.json
pnpm-lock.yaml

spotted in https://github.com/nuxt/nuxt/issues/32494.
while there should be no real problem in depending on nuxt/schema (as I think the linked bug must be a bug in nuxt or a package manager bug), I think we probably don't need to have an explicit dependency as this should be pulled in using whatever version of nuxt someone is using.

fix(deps): do not depend on `@nuxt/schema`
